from loadJson import *

minions = loadJson("minions")
toChanged = {
    'atramedes': 4,
    'ball of minions': 4,
    'baltharak' : 1,
    'bejeweled duelist' : 2,
    'briarback bookie': 2,
    'carbonic copy': 4,
    'champion of the primus': 5,
    'crab': 1,
    'diablo, lord of terror': 0,
    'friend of a friend': 5,
    'golden monkey': 1,
    'mechapony': 1,
    'mechorse': 1,
    'murozond': 5,
    'picky eater': 1,
    'rendle the mistermind': 4,
    'rusted reggie': 1,
    'spark-ling': 3,
    'tortollan blue shell': 5,
    'uther the lightbringer': 6,
    'bubblette': 1,
    'cattlecarp of n\'zoth': 1,
    'cubling': 1,
    'defiant shipwright': 2,
    'impulsive trickster': 2,
    'jo-e bot': 1,
    'manasaber': 1,
    'mecharoo': 1,
    'razorfen geomancer': 1,
    'scallywag': 1,
    'shifter zerus': 3,
    'shudderling': 1,
    'shudderskull': 1,
    'abominable amalgam': 1,
    'cogwork copter':2,
    'guard bot':1,
    'humming bird': 2,
    'leapfrogger': 2,
    'murloc tidehunter':1,
    'reef riffer':2,
    'upbeat flutist':2,
    'vulgar homunculus':1,
    'whelp smuggler':2,
    'accord-o-tron':3,
    'bannerboar':4,
    'bilgewater mogul':4,
    'imp gang boss':3,
    'keyboard igniter':3,
    'moon-bacon jazzer':3,
    'necrolyte':4,
    'prickly piper':3,
    'prophet of the boar':2,
    'roadboar':2,
    'rylak metalhead':4,
    'silverback patriarch':1,
    'sun-bacon relaxer':1,
    'thawed champion':3,
    'tough tusk':2,
    'watfin':3,
    'waxrider togwaggle':2,
    'zesty shaker':3,
    'blade collector':4,
    'briny bootlegger':3,
    'bronze warden':3,
    'dancing barnstormer':4,
    'dazzling lightspawn':4,
    'deep blue crooner':4,
    'houndmaster':3,
    'lovesick balladist':4,
    'malchezaar, prince of dance':4,
    'master gadrin':4,
    'nexus lord':4,
    'palescale crocolisk':5,
    'peggy brittlebone':4,
    'plagued tidewalker':4,
    "prestor's pyrospawn":4,
    'prized promo-drake':4,
    'screwjank clunker':3,
    'thorncaptain':1,
    'upbeat upstart':4,
    'bristleback knight':5,
    'cyborg drake':5,
    'festeroot hulk':5,
    'general drakkisath':5,
    'goldgrubber':4,
    'imposing percussionist':4,
    "insatiable ur'zul":5,
    'si:sefin':5,
    'sub scrubber':4,
    'submersible chef':5,
    'tichondrius':5,
    'underhanded dealer':5,
    'vanessa vancleef':5,
    'choral mrrrglr':6,
    'colossus of the sun':6,
    "cultist s'thara":6,
    'drakonid enforcer':4,
    'dread admiral eliza':6,
    'famished felbat':6,
    'greta gold-gun':6,
    'nathanos blightcaller':6,
    'octosari, wrap god':6,
    'safeguard':6,
    'the beast':3,
    'twilight emissary':3,
    "mal'ganis":5
}
for i in minions:
    if minions[i]["tier"] == "manualGetTier":
        for z in toChanged:
            if i.replace(' (golden)','') == z:
                minions[i]["tier"] = toChanged[z]
        
            
        

with open("minions.json", "w") as f3:
    json.dump(minions, f3, indent=4)

